-- 11: Major Socials Migration — RETIRED
-- Legacy ig_*/yt_*/tt_* inline columns never existed on hb_talent.
-- Instagram/YouTube/TikTok data is written directly to hb_socials by enrichers.
-- No action needed.
